stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cuijx/gin-demo
      pushRemote: true
      registry: 127.0.0.1:34748
  when:
    event:
      include:
      - push
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deploy.yaml
  when:
    event:
      include:
      - push
timeout: 180
branch:
  include:
  - master
notification: {}
