stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cuijx/gin-demo
      pushRemote: true
      registry: index.docker.io
  when:
    event:
      include:
      - push
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deploy.yaml
  when:
    event:
      include:
      - push
timeout: 180
branch:
  include:
  - master
notification: {}
