apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: cuijx/executor
    args: ["--dockerfile=/code/go-demo/gin-demo/Dockerfile",
            "--context=/code/go-demo/gin-demo/",
            "--skip-tls-verify=true",
            "--destination=cuijx/gin-demo:v0.0.1"]
    volumeMounts:
      - name: code
        mountPath: /code/go-demo
      - name: docker-config
        mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: code
      persistentVolumeClaim:
        claimName: code-claim
    - name:  docker-config
      configMap:
        name: docker-config
