apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs
---
apiVersion: batch/v1
kind: Job
metadata:
  name: clone-job
spec:
  template:
    metadata:
      name: clone-job
    spec:
      containers:
      - name: clone-job
        image: cuijx/atom-git:v0.0.1
        command: ["git", "clone", "https://github.com/cuijxin/gin-demo.git"]
        volumeMounts:
        - mountPath: "/code/go-demo"
          name: mypd
      restartPolicy: Never
      volumes:
      - name: mypd
        persistentVolumeClaim:
          claimName: code-claim

