apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gin-demo
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: gin-demo
    spec:
      containers:
      - name: gin-demo
        image: cuijx/gin-demo
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gin-demo
  name: gin-demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gin-demo
  sessionAffinity: None
  type: NodePort
